### ISSUE TITLE
ERROR Bad state: No element

### ISSUE THREAD

**Issue by water783** [zapstore/zapstore-cli#21]
Hi, I got this error message after entering NSEC

```
ERROR Bad state: No element

#0      _LinkedHashSetMixin.first (dart:collection-patch/compact_hash.dart:794)
#1      finalizeEvents (package:zapstore_cli/commands/publish/events.dart:16)
#2      publish (package:zapstore_cli/commands/publish.dart:188)
<asynchronous suspension>
#3      PublishCommand.run (package:zapstore_cli/main.dart:147)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#5      main (package:zapstore_cli/main.dart:34)
<asynchronous suspension>
```

**Comment by franzaps** [comment]
Hi, please share your zapstore.yaml snippet here. Did you include the artifacts array?

**Comment by franzaps** [comment]
And which arguments are you running the program with?

**Comment by water783** [comment]
> And which arguments are you running the program with?

```
0xchat:
  android:
    identifier: com.oxchat.nostr
    name: 0xchat
    description: 0xchat is a secure chat app built on the Nostr protocol. It prioritizes security, featuring private key login, encrypted private chats and contacts, encrypted group chats, and lightning payments(Cashu). 
    repository: https://github.com/0xchat-app
    license: MIT
    artifacts:
      - 0xchat-v%v-beta.apk
```

and i run with -a -n

**Comment by franzaps** [comment]
Thank you! It should be fixed in the next release

**Comment by franzaps** [comment]
@water783 the repository is incorrect, though, shouldn't it be https://github.com/0xchat-app/0xchat-app-main ?

**Comment by water783** [comment]
It seems I'm still unable to work properly. I am using zapstore-cli v0.1.0

```shell
zapstore-cli % ./zapstore publish 0xchat
[dotenv] Load failed: file not found: File: '.env'
Publishing 0xchat android app...
✔ Fetched metadata from Github
✔ Fetched package: https://github.com/0xchat-app/0xchat-app-main/releases/download/v1.3.4-beta.2/0xchat-v1.3.4-beta.2.apk
⠙ Parsing APK...
ERROR ShellException(sh -c "apksigner verify --print-certs /var/folders/44/d34x41_905zc8gf8dzlk95mc0000gn/T/750d871b27de331e4eb75c32fc27d39494ac340ef8b82230617a466cae85ad1a.apk | grep SHA-256", exitCode 1)
```

Then, when I run the command again, it prompts "nothing to do", but I don't see the latest `v1.3.4-beta.2` of 0xchat on zapstore.

```shell
Publishing 0xchat android app...
✔ Fetched metadata from Github
✔ Latest 0xchat-app/0xchat-app-main release already in relay, nothing to do
```

**Comment by franzaps** [comment]
Issue probably related to the fact 0xchat was already in the relay but signed by zap.store. I removed it. 

Also third-party publishing is not allowed by default, I just whitelisted your npub (npub1tm99pgz2lth724jeld6gzz6zv48zy6xp4n9xu5uqrwvx9km54qaqkkxn72) in the relay for `com.oxchat.nostr`, so please sign with that one.

And try again using the following:

```yaml
0xchat:
  android:
    name: 0xchat
    description: 0xchat is a secure chat app built on the Nostr protocol. It prioritizes security, featuring private key login, encrypted private chats and contacts, encrypted group chats, and lightning payments(Cashu). 
    repository: https://github.com/0xchat-app/0xchat-app-main
    license: MIT
    artifacts:
      - 0xchat-.*.apk
```

**Comment by water783** [comment]
thx, but i still have this issue

```
Publishing 0xchat android app...
✔ Fetched metadata from Github
✔ Latest 0xchat-app/0xchat-app-main release already in relay, nothing to do
```

**Comment by franzaps** [comment]
Ugh. Forgot to remove the metadata. Try again, it should work now.

If it doesn't, and in general if you want to go ahead anyway, you can pass `--overwrite-release`.

**Comment by water783** [comment]
thx, it works
